#!/usr/bin/env bash
# Installs nginx server
apt-get update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
server {
    listen 80;
    ...
}
echo "Hello World!" > /var/www/html/index.html
service ngnix start

